# Generated by Django 5.2.17 on 2026-09-22 01:08

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=250)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sede',
                'verbose_name_plural': 'sedes',
                'db_table': 'sedes',
                'ordering': ('nombre',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='sede_nombre_unico_sin_mayusculas', violation_error_message='Ya existe una sede con ese nombre.')],
            },
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('superficie', models.CharField(choices=[('cemento', 'Cemento'), ('polvo_ladrillo', 'Polvo de ladrillo')], max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canchas', to='instalaciones.sede')),
            ],
            options={
                'verbose_name': 'cancha',
                'verbose_name_plural': 'canchas',
                'db_table': 'canchas',
                'ordering': ('sede__nombre', 'nombre'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('sede'), name='cancha_nombre_unico_por_sede_sin_mayusculas', violation_error_message='Ya existe una cancha con ese nombre en esta sede.')],
            },
        ),
    ]
